### ISSUE TITLE
Chromium crashes when playing a video files

### ISSUE THREAD

**Issue by buddhike** [boundarydevices/meta-boundary#1]
I've built sato image with this layer. However, when I play a video in Chromium, it crashes. It also crashes if I attempt to visit http://html5test.com

What are the steps to follow to build Chromium with HTML5 video support?

**Comment by iancoolidge89** [comment]
Add chromium-codecs-ffmpeg and chromium-codecs-ffmpeg-bin. The ffmpeg library needs to be in the chromium bin path. See our append recipe here: https://github.com/boundarydevices/meta-boundary/blob/jethro/recipes-browser/chromium/chromium_40.0.2214.91.bbappend

I'll be adding these two recipes to the boundary-eval-image as well, soon.

**Comment by buddhike** [comment]
Thanks! 
I didn't include ffmpeg packages. Will build it again with them.

If I have cloned meta-boundary repo and checkout jethro branch, the build should pickup your above patch right?

**Comment by iancoolidge89** [comment]
You'll need to add meta-boundary to the bblayers.conf file.

**Comment by buddhike** [comment]
Thanks, it worked!
