### ISSUE TITLE
Re-write of zeus branch history

### ISSUE THREAD

**Issue by jdegges** [boundarydevices/meta-boundary#10]
It appears that the zeus branch was recently re-written. All commits since Oct 15 2019 have been updated.

Previously:
> commit 13eade896b9e4de66e35adc5c6b84bffb9c0f1b9 (m/zeus)
> Author:     Chris Dimich <chris.dimich@boundarydevices.com>
> AuthorDate: Fri Feb 21 14:51:00 2020 -0800
> Commit:     Chris Dimich <chris.dimich@boundarydevices.com>
> CommitDate: Fri Feb 21 14:51:00 2020 -0800
>
>     Remove xserver-xorg patch. This is apart of meta-freescale
> 
> ... snip many commits...
> 
> commit 3360fe0b4c85fb8e898d07b260656cb83466223d
> Author:     Chris Dimich <chris.dimich@boundarydevices.com>
> AuthorDate: Tue Oct 15 15:49:26 2019 -0700
> Commit:     Chris Dimich <chris.dimich@boundarydevices.com>
> **CommitDate: Tue Oct 15 15:49:26 2019 -0700**
>
>     Initial commit for warrior branch

Now:
> commit 03877f0a9d5b0e59a892ec4cb57c1981ec5a9538 (HEAD, origin/zeus)
> Author:     Chris Dimich <Chris.Dimich@boundarydevices.com>
> AuthorDate: Fri Mar 20 21:02:33 2020 -0700
> Commit:     Chris Dimich <Chris.Dimich@boundarydevices.com>
> CommitDate: Fri Mar 20 21:02:33 2020 -0700
>
>     imx-mkimage: Fix recipe name syntax
>    
>     Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>
>
> ... snip many commits...
>
> commit f4e096cc65010cf91f91400e2ff48fbc4cdaa712
> Author:     Chris Dimich <chris.dimich@boundarydevices.com>
> AuthorDate: Tue Oct 15 15:49:26 2019 -0700
> Commit:     Chris Dimich <Chris.Dimich@boundarydevices.com>
> **CommitDate: Fri Mar 13 16:22:40 2020 -0700**
>
>     Initial commit for warrior branch

Note commit date of all commits since "Initial commit for warrior branch". Originally these commits were staggered since Oct 15. Now they all appear to have been committed on March 13th.

The master branch had been behind the zeus branch for a while and it looks like it was recently updated. Perhaps zeus was accidentally force-pushed to at this time?

Consider restoring the original state of the zeus branch--it will make this repository easier to work with.

**Comment by chrisdimich** [comment]
Hi Joey,

This was a mistake. We apologize and it will not happen again. Please grab
the latest and you should be good. Also note that the commit dates are
actually in tact for example:

https://github.com/boundarydevices/meta-boundary/commit/a637897c3701cb206f74a21dfaeccdd5dd1df9cc

Shows committed on Feb 10.

Thanks,

Chris Dimich
Boundary Devices, LLC
www.boundarydevices.com
7 Orchard Road, Suite 102*｜*Lake Forest, CA 92630

**Comment by gibsson** [comment]
Since this was a one-time error, let's close this issue. Let us know if you ever see that problem again, it should never happen.
