### ISSUE TITLE
gstreamer-imx on i.MX8

### ISSUE THREAD

**Issue by JustBenj** [boundarydevices/meta-boundary#8]
In [boundary-wayland.conf](https://github.com/boundarydevices/meta-boundary/blob/master/conf/distro/boundary-wayland.conf) you comment there's no gstreamer-imx for iMX8 yet, but there actually is one in development.

It is being developed on the [V2 branch](https://github.com/Freescale/gstreamer-imx/tree/v2). I'm not familiar with how Yocto builds work, but I would be interested in learning how to add this package to my board so I can take advantage of the imxg2dcompositor.

Currently on the iMX8 with the standard compositor it's horribly slow (I assume because it's using the CPU).

**Comment by chrisdimich** [comment]
Hi Benji,

You are correct that is in development, however meta-freescale is not using this yet. If you refer to the recipe "gstreamer1.0-plugins-imx_git.bb" inside meta-freescale/recipes-multimedia/gstreamer on the master branch you will see that COMPATIBLE_MACHINE does not include imx8 and they are still using master branch and not v2. We will wait for this V2 branch to be officially released before using it.

Thanks,
Chris Dimich
